### ISSUE TITLE
RFE: Add round-trip checking

### ISSUE THREAD

**Issue by DemiMarie** [beevik/etree#100]
XML-DSIG relies crucially on round-trip stability, which `encoding/xml` does not guarantee.  This can be worked around by reserializing and then reparsing a tree, and checking that the reparsed tree is identical to the original.

**Comment by beevik** [comment]
This package is based on `encoding/xml` and thus inherits any of its limitations.

**Comment by DemiMarie** [comment]
> This package is based on `encoding/xml` and thus inherits any of its limitations.

Would it be possible to add an API function for round-trip checking?

**Comment by beevik** [comment]
You mean like a way to compare two XML documents to see if they are identical?

**Comment by DemiMarie** [comment]
A way to make sure that the XML did, in fact, get parsed correctly.  This can be done by re-serializing the parsed XML and checking that the serialized XML is bitwise identical to the original.  For an arbitrary tree, this can be done by serializing and reparsing the tree and checking that the reparsed tree is identical to the original.

**Comment by beevik** [comment]
This feels like something that can be easily done at a higher layer than etree. It also feels a bit out of bounds for etree (just as it would be out of bounds for `encoding/xml`).
