### ISSUE TITLE
Can you share performance benchmarks or steps to measure it  for this tool?

### ISSUE THREAD

**Issue by ShriprasadM** [beevik/etree#103]
We are planning to use this library in our project. Before integrating it, we would like to know how this tool performance in simple and complex XML documents, in terms of adding, deleting or modifying existing nodes

**Comment by ShriprasadM** [comment]
@beevik  : do we have any performance benchmarks for this library. Can you share the details?

**Comment by beevik** [comment]
I have not run benchmarks, but you are free to write some and run them yourself.
