### ISSUE TITLE
a bug of Element.Text()

### ISSUE THREAD

**Issue by west-wind-luwei** [beevik/etree#106]
```
xmlStr := `
<a>
    123
    <!-- comment -->
    456
</a>
`
fmt.Println(a.Text())
```
```
    123
```
The output does not contain 456.

Using "encoding/xml" package, can get the complete output
```
    123

    456
```

**Comment by beevik** [comment]
This bug has been fixed in https://github.com/beevik/etree/commit/ae6f9e68c82ff48b11f6fb003b0724d08708991b
