### ISSUE TITLE
Unexpected <></> when adding outer layer

### ISSUE THREAD

**Issue by davidasync19** [beevik/etree#112]
I tried to add outer XML to my XML.
assume my XML is `<Foo></Foo>` but when trying to add the outer layer there's an additional empty tag like `<></>`
how to remove that.

Here's my snippet
```go
func main() {
	result := etree.NewDocument()

	if err := result.ReadFromString("<Foo></Foo>"); err != nil {
		log.Fatal(err.Error())
	}

	doc := etree.NewDocument()
	root := doc.CreateElement("Envelope")
	root.Space = "soap"

	soapHeader := doc.CreateElement("Header")
	soapHeader.Space = "soap"


	soapBody := doc.CreateElement("Body")
	soapBody.Space = "soap"

	root.AddChild(soapHeader)
	root.AddChild(soapBody)
	root.AddChild(result)

	doc.Indent(2)
	println(doc.WriteToString())
}
```

and the result is
```xml
<soap:Envelope>
  <soap:Header/>
  <soap:Body/>
  <><Foo/></>
</soap:Envelope>
```

I expected the result is
```xml
<soap:Envelope>
  <soap:Header/>
  <soap:Body/>
  <Foo/>
</soap:Envelope>
```

There's <></> between <Foo/>

**Comment by ericschmar** [comment]
I'm having this same issue. Did you find a work around?

**Comment by giesan** [comment]
Replace 
`root.AddChild(result)`
by
`root.AddChild(result.Root())`

Result is a document and AddChild expects an element.

**Comment by beevik** [comment]
Just FYI, your discovered solution is the correct way to do this.  The document is a container for the Root element.
