### ISSUE TITLE
how to pretty print when writing back

### ISSUE THREAD

**Issue by liesauer** [beevik/etree#116]
```xml
<root>
  <first />
</root>
```

if i insert a `second` element, the xml will become like this

```xml
<root>
  <first />
  <second /></root>
```

**Comment by beevik** [comment]
Closed, as the issue does not describe the problem that needs to be solved.

**Comment by liesauer** [comment]
this is my xml
```
<root>
  <first />
</root>
```

and i am trying to insert a second element into `root`

```go
doc := etree.NewDocument()

doc.ReadFromFile(xmlFile)

root := doc.FindElement("./root")

root.CreateElement("second")

doc.WriteSettings.UseCRLF = true

bytes, _ := doc.WriteToBytes()
```

expected result
```xml
<root>
  <first />
  <second />
</root>
```

actual result
```xml
<root>
  <first />
  <second /></root>
```

should be clear enough, thanks for the responsing.

**Comment by beevik** [comment]
The etree document has no way of knowing how a document has been formatted with respect to whitespace, so it cannot infer that it needs to insert a newline after creating a child element.  However, you can call `Indent` before writing the document to force whatever indenting you like.  For example:

```
doc.Indent(2)
bytes, _ := doc.WriteToBytes()
```

**Comment by liesauer** [comment]
thanks.
