### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by btagrass** [beevik/etree#118]
It works fine in version 1.1.2
doc := etree.NewDocument()
doc.ReadSettings.CharsetReader = charset.NewReaderLabel
err := doc.ReadFromBytes([]byte("utf-8 string"))
if err != nil {
    return err
}

It doesn't work in version 1.1.3,what's wrong?

**Comment by beevik** [comment]
I am unable to repro your error with the following unit test:
```go
func TestUTF8(t *testing.T) {
	doc := NewDocument()
	doc.ReadSettings.CharsetReader = charset.NewReaderLabel
	err := doc.ReadFromBytes([]byte("utf-8 string"))
	if err != nil {
		t.Fatalf("etree: Failed to handle string")
	}
}
```

Can you provide more detail? What was the error?

**Comment by btagrass** [comment]
func TestUTF8(t *testing.T) {
	doc := NewDocument()
	doc.ReadSettings.CharsetReader = charset.NewReaderLabel
	err := doc.ReadFromBytes([]byte("<?xml version=\"1.0\" encoding=\"GB2312\"?>\n<Notify>\n<CmdType>Keepalive</CmdType>\n<SN>243</SN>\n<DeviceID>34020000001320000001</DeviceID>\n<Status>OK</Status>\n<Info>\n</Info>\n</Notify>\n"))
	if err != nil {  // Never run here
		t.Fatalf("etree: Failed to handle string")
	}
}

**Comment by beevik** [comment]
Thank you for the additional information. I have reverted a feature introduced in v1.1.3. This should prevent the hang bug you were seeing.
