### ISSUE TITLE
Does this library supports XInclude standards for XML document?

### ISSUE THREAD

**Issue by Leon-Zhang** [beevik/etree#119]
As title, have tried using xi:include node in xml file to be parsed, but seems xi:include not working.

**Comment by beevik** [comment]
etree is based on the go standard library's `encoding/xml` package, so it inherits both the features and the limitations of that package. As far as a I know, the `encoding/xml` package does not include support for XInclude, so neither does etree.

The etree package should be capable of parsing the `<xi:include>` element, but it will not automatically include the referenced document.
