### ISSUE TITLE
Is there any way to get the comments of a document?

### ISSUE THREAD

**Issue by davi4046** [beevik/etree#121]
I'm interested in getting the comment that precedes an element. Is this possible in any way? 

It seems that there are ways to create comments and manipulate them but I couldn't find any methods for finding comments.

**Comment by beevik** [comment]
There is not currently an *elegant* way to do this, but it is possible.  

If you have the element in question, you can access its `Parent()` and its `Index()` within that parent element's list of children.  You can then search through the parent's child tokens for comment tokens preceding that index.

**Comment by beevik** [comment]
Here is a quick and dirty helper function that searches for a comment preceding an element:

```go
func findParentPrefixComment(e *etree.Element) *etree.Comment {
	index := e.Index()
	p := e.Parent()

	for i := index; i >= 0; i-- {
		if comment, ok := p.Child[i].(*etree.Comment); ok {
			return comment
		}
	}

	return nil
}
```

It's not very sophisticated.  (It searches for the first comment preceding the element, even if other elements are found after the comment.)  But you can easily modify it to suit your use case.

**Comment by davi4046** [comment]
Okay, I sort of tried this but I think it didn't work because I tried to cast an *etree.Element to *etree.Comment.

I haven't had time to try these out but I'm thinking p.Child[i] is an etree.Token or some other type than etree.Element since it can be cast.

Anyways, thank you for the help and for this awesome library ;)

**Comment by beevik** [comment]
Yes, `etree.Token` is an interface type that `etree.Element` and `etree.Comment` implement.  So you can do a type assertion (i.e., "cast") to treat the token like one of its implementing types.

I will close this comment, and good luck with your project.
