### ISSUE TITLE
i don't wanna the string text to be escaped, how can i achieve that

### ISSUE THREAD

**Issue by tangyiming** [beevik/etree#124]
Hi there, 

   I don't wanna the string text to be escaped when i use `SetText(str)`, how can i achieve that. I cannot find any setting i can control this behavior.

   Do i need use `CreateElement` or `CreateAttr` line by line?

Thanks for your help.

**Comment by beevik** [comment]
Can you be more specific about what kind of text strings you don't wish to be escaped? The reason is escape characters like '&' and '"' is because noncompliant XML would otherwise be produced.

**Comment by eamon-t-2023** [comment]
@beevik actually i want to insert a maven dependency to the pom.xml, but i don't want to set every node line by line.
for example:
```
<dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>3.8.8</version>
            <scope>provided</scope>
</dependency>
```
I thought I can add those content just in one line like: 
```
CreateElement("dependency").SetText(<groupId>org.apache.maven</groupId>\n"+
            "<artifactId>maven-plugin-api</artifactId>\n"+
            "<version>3.8.8</version>\n"+
            "<scope>provided</scope>")
```
but the <,> are escaped. 

after all, it's ok. i finished this thing by calling more times of CreateElement().SetText();

**Comment by beevik** [comment]
`SetText` is not intended to be used to create elements or manipulate the XML hierarchy. It's used only to add character data to an element.  If you need to manipulate the XML hierarchy, the etree package expects you to do it with calls to `CreateElement`.

In your example, the proper way to update the document would be:
```go
dependency := doc.CreateElement("dependency")
dependency.CreateElement("groupId").SetText("org.apache.maven")
dependency.CreateElement("artifactId").SetText("maven-plugin-api")
dependency.CreateElement("version").SetText("3.8.8")
dependency.CreateElement("scope").SetText("provided")
```

**Comment by eamon-t-2023** [comment]
by i think you can close this issue now. thanks
