### ISSUE TITLE
if my text contains some string likes '<br>',but i dont wanna to escape them,how can i do

### ISSUE THREAD

**Issue by banmashushu** [beevik/etree#125]
i  have read the source code，the setting CanonicalText  is not used

**Comment by beevik** [comment]
Given the way XML works, that's not really possible.

It sounds like you're trying to use etree as a parser for HTML, which I wouldn't recommend.  HTML is not XML comformant.

**Comment by banmashushu** [comment]
thanks for your answer，I will control it at the source
