### ISSUE TITLE
XPath string literal syntax does not accept double quotes

### ISSUE THREAD

**Issue by hut8** [beevik/etree#126]
Hey there. Thanks for an awesome library, and for doing such a good job maintaining it. I have a small issue that has a workaround, but tripped me up for a bit:

```go
doc.FindElements(`//Data[@name='the-name']`) // works
```

```go
doc.FindElements(`//Data[@name="the-name"]`) // doesn't work
```

So, the quotes ("double quotes") fail, but the apostrophe ("single quote") works.

[The spec I'm looking at](https://www.w3.org/TR/xpath-31/#abbrev) gives this example:

> `para[@type="warning"]` selects all para children of the context node that have a type attribute with value warning

> For example, a path expression `para[@type="warning"]` is short for `child::para[attribute::type="warning"]`

When I was figuring out what my bug was (this was actually the first time I used XPath ever), I used https://www.freeformatter.com/xpath-tester.html, which accepted double quotes.

https://www.w3.org/TR/xpath-31/#prod-xpath31-StringLiteral says that string literals can be written using either type of quote.

**Comment by beevik** [comment]
I modeled the path query syntax after the one used by Python's element tree module, which only supports single quotes.  But I see no reason why this package shouldn't support double-quotes, so I just checked in a change to add that support.

Thanks for the suggestion!

**Comment by beevik** [comment]
By the way, I should point out that the path system built into etree is documented to be "XPath-like" and will never be fully XPath-compliant. The XPath spec is too complicated for a relatively simple package like this.

I just wanted to help set expectations for when you discover other XPath features etree doesn't support.
