### ISSUE TITLE
Signature of FindElements...

### ISSUE THREAD

**Issue by comeAndGo** [beevik/etree#132]
Hi -

Recently downloaded beevik/etree - Release v1.3.0

Finding in the source this code:

`func (e *Element) FindElements(path string) []*Element {....`

Indicating that `FindElements` returns 1 value, `[]*Element ` . But when calling this function, it is returning 2 values, an integer value and `[]*Element` .  Calling ` elems1 := range doc.FindElements(".//Process//Params") {...` returns only an integer value, not `[]*Element` .

Must call like this  ` i, elems1 := range doc.FindElements(".//DBProcess//DBParams") {...`  to get back `[]*Element` for `elems1 `

This doesn't match the signature in the source code, nor does it seem to make sense: If the function returns 2 values, it should not compile if I'm only assigning one value to the return.

Am I missing something? Outdated code? Please help/explain.

Tnx
MNG

**Comment by beevik** [comment]
The `range` operator is a go feature that is intended to be used with for loops.  For instance:
```go
for i, element := range doc.FindElements(".//Processes/Params") {
    fmt.Printf("Index #%d: %s\n", i, element.Tag)
}
```

If you're trying to get the array of elements returned by `FindElements`, just exclude the `range` operator.
