### ISSUE TITLE
How to access sibling element using Go with etree XML package?

### ISSUE THREAD

**Issue by comeAndGo** [beevik/etree#133]
Hello -

PLEASE - take a look at this question I posted on StackOverflow.com. I am working on an important project and this issue has me stumped:

[**_How to access sibling element using Go with etree XML package?_**](https://stackoverflow.com/questions/78421818/how-to-access-sibling-element-using-go-with-etree-xml-package)

Thank You!

**Comment by comeAndGo** [comment]
Answered on SO.

**Comment by beevik** [comment]
After reading your question and the StackOverflow suggestion, I realized there wasn't really an elegant way to traverse sibling elements using etree.  So I just committed a change that introduces the `NextSibling` and PrevSibling` element functions.

See: https://github.com/beevik/etree/commit/cc099d9d9748de91c91e11699f66fd5a087e5477
