### ISSUE TITLE
Guidance Needed: Removing XML Declaration in etree

### ISSUE THREAD

**Issue by call-stack** [beevik/etree#135]
Hello,

I am currently trying to utilize this library for XML processing in Go and I am encountering a challenge with removing the XML declaration from the output string. Despite several attempts, I haven't found a straightforward method to omit the XML declaration when using the `WriteToString` function.

Could someone please guide me on how to achieve this? Are there specific settings or procedures within this lib that I should use to ensure the XML declaration is consistently omitted from the output?

Thank you in advance for your assistance!

**Comment by beevik** [comment]
It is admittedly somewhat difficult to manipulate non-element tokens from an etree document.  But it is possible. For example, the following code searches through the root level's child tokens for an "xml" processing instruction (i.e. the XML declaration) and removes it:

```go
for _, t := range doc.Child {
	if p, ok := t.(*ProcInst); ok && p.Target == "xml" {
		doc.RemoveChild(p)
		break
	}
}
```

**Comment by call-stack** [comment]
Thank you for the detailed explanation and the code snippet. It definitely clarifies how to manipulate non-element tokens using etree.
Considering this approach, would it be a good idea to encapsulate this functionality into a method that can be part of this lib itself? This could simplify the process for users who need to manipulate processing instructions or other non-element tokens in similar ways. What do you think about exposing such a method in the library itself?

**Comment by call-stack** [comment]
The code provided successfully removes the XML declaration. However, when invoking doc.WriteToString() afterward, it results in an empty line along with document content.

**Comment by beevik** [comment]
Yes, each element's Child tokens includes white-space text-only tokens.  You can either continue to scan for CharData tokens after finding the ProcInst and remove them as well, or you can just re-indent the document using doc.Indent() after removing the line.
