### ISSUE TITLE
Reject directives by default

### ISSUE THREAD

**Issue by DemiMarie** [beevik/etree#140]
XML directives have numerous problems:

- They are very difficult to parse correctly unless one uses a parser generator.  This lead to security holes in the past.
- They are a major source of security holes:
  - Exponential entity expansion
  - Quadratic entity expansion
  - External entity retrieval
  - External DTD retrieval
- They are only allowed before the opening element.

.NET 4.5.2+ rejects them by default and I recommend doing the same.

**Comment by beevik** [comment]
Isn't it the case that encoding/xml ignores external entities?

Turning off directives is a breaking change.

**Comment by DemiMarie** [comment]
Perhaps this could be made opt-in, then?  SAML implementations certainly need neither directives nor processing instructions, and may want to reject comments as well.

**Comment by beevik** [comment]
Unfortunately opt-in is also a breaking change.

If go's `encoding/xml` package ignores external entity declarations, can you explain how this is a security risk?

**Comment by DemiMarie** [comment]
The problem is that the same XML might also be parsed by something that does _not_ ignore XML external entities.

Unfortunately the more secure behavior will need to be off by default, sadly.

**Comment by beevik** [comment]
OK I appreciate the feedback.  I will close this issue but will add an option to disable directive parsing as an opt-in behavior (even if it's not an ideal solution to the problem).
