### ISSUE TITLE
New line after BOM

### ISSUE THREAD

**Issue by suntong** [beevik/etree#16]
The `doc.WriteTo` is adding an extra new line after BOM. I've illustrate it with et_dump.go and et_dump.xml, which you can find under https://github.com/suntong/lang/blob/master/lang/Go/src/xml/. 

Here is the result:

```
$ go run et_dump.go | diff -wU 1 et_dump.xml -
--- et_dump.xml 2016-03-08 16:40:41.667010100 -0500
+++ -   2016-03-08 16:40:57.842603083 -0500
@@ -1,4 +1,4 @@
-ï»¿<?xml version="1.0" encoding="utf-8"?>
+ï»¿
+<?xml version="1.0" encoding="utf-8"?>
 <bookstore xmlns:p="urn:schemas-books-com:prices">
-
   <book category="COOKING">
@@ -9,3 +9,2 @@
   </book>
-
   <book category="CHILDREN">
...
@@ -34,3 +31,2 @@
   </book>
-
 </bookstore>
\ No newline at end of file
```

I.e., an extra new line is added after BOM. This seems to be a trivial issue, but will cause my Microsoft Visual Studio failed to recognize the webtest file such dump creates. :-(

Please consider removing the added extra new line. 

Thanks

**Comment by suntong** [comment]
Hi, do you agree with removing the added extra new line? Thx

**Comment by suntong** [comment]
I still think the request is reasonable. 
Maybe abandoned project...?

**Comment by beevik** [comment]
Sorry, just noticed the issue.  Examining now.

**Comment by suntong** [comment]
Oh, thank god. So glad that the project is still maintained. Thanks for checking.

**Comment by beevik** [comment]
Ok all fixed.  Thanks for the bug report!

**Comment by suntong** [comment]
Thanks a lot for the fix!
