### ISSUE TITLE
(X)Path OR search

### ISSUE THREAD

**Issue by suntong** [beevik/etree#19]
I checked https://godoc.org/github.com/beevik/etree#Path and it seems the [(X)Path OR operator for different nodes searching](http://stackoverflow.com/questions/5350666/xpath-or-operator-for-different-nodes) is not there. 

Please consider providing that feature, as it'd be very useful, but not too difficult to do. 

To recap, from above stackoverflow Q:

The `XPath` OR operator of 

`//bookstore/book/title or //bookstore/city/zipcode/title`

is expressed as:

`//bookstore/book/title|//bookstore/city/zipcode/title`

Thanks!

**Comment by beevik** [comment]
Please transfer discussion to: https://github.com/beevik/etree/pull/20
