### ISSUE TITLE
Failure to parse '/' in xpath values

### ISSUE THREAD

**Issue by enochtsang** [beevik/etree#24]
When '/' is not used as a path separator in a path, like in the example below, etree's xpath compilation will fail. 

`//http[@internet='web']//url[@pattern='/web/app' ]`

This is due to line 192 in path.go
```go
	for _, s := range strings.Split(path, "/") {
```

Any suggestions for a fix?

**Comment by enochtsang** [comment]
Addressed by open PR https://github.com/beevik/etree/pull/25

**Comment by beevik** [comment]
Thanks for reporting this bug.  Thanks also for the pull request.  I decided to go with my own fix for this bug, however, as I didn't want to add the depdendency on regexp.
