### ISSUE TITLE
About the TestAddChild()

### ISSUE THREAD

**Issue by suntong** [beevik/etree#29]
About the TestAddChild(), 

[Line 316 to 318](https://github.com/beevik/etree/blob/012da2a5335219c3181304e310edeb482b342de0/etree_test.go#L316-L318) is, 

```go
	testdoc := `<book lang="en">
  <t:title>Great Expectations</t:title>
  <author>Charles Dickens</author>
`
```

I.e., the `<t:title>` and `<author>` are **not** enclosed within `<book>` but **parallel** to it. Right? (Ref: [L333](https://github.com/beevik/etree/blob/012da2a5335219c3181304e310edeb482b342de0/etree_test.go#L333))
If so, the [`FindElements("//book/*")`](https://github.com/beevik/etree/blob/012da2a5335219c3181304e310edeb482b342de0/etree_test.go#L329) should return empty right? I.e., the [`root.AddChild(e)` result](https://github.com/beevik/etree/blob/012da2a5335219c3181304e310edeb482b342de0/etree_test.go#L339-L342) seems incorrect to me. 

What I'm missing? Thx.

**Comment by beevik** [comment]
I'm surprised it works, since the </book> end element should be there. I guess the go xml library doesn't care about missing end elements in certain cases.

I submitted a fix to the test, nonetheless.  Thanks.

**Comment by suntong** [comment]
Hmm.., wouldn't [L333](https://github.com/beevik/etree/blob/012da2a5335219c3181304e310edeb482b342de0/etree_test.go#L333) be 

```
<book lang="en">
  <t:title>Great Expectations</t:title>
  <author>Charles Dickens</author>
</book>

```

then? How come it's only `<book lang="en"/>`?

**Comment by beevik** [comment]
It's because the adding of the children to doc2 removed them from doc1.

**Comment by suntong** [comment]
Gotya. Thx.

**Comment by suntong** [comment]
Hm, sorry to bother you, 

why it is OK for me to use `doc1.Copy().FindElements("//book/*")` but not `doc1.FindElements("//book/*").Copy()`, which gave me the following error:

` doc1.Element.FindElements("//book/*").Copy undefined (type []*etree.Element has no field or method Copy)
`

I can't figure out why. Thx.
