### ISSUE TITLE
Need/How to set prefix

### ISSUE THREAD

**Issue by suntong** [beevik/etree#32]
When outputting xml, the indentation is not the only control necessary -- prefix string is necessary as well, for the xml chunks that are not starting at the root level. Ref:  https://godoc.org/encoding/xml#MarshalIndent, which has two controls: `prefix, indent string`.

**Comment by beevik** [comment]
I've decided against implementing this feature.  If someone wants this behavior, it would be pretty easy to achieve with a combination of `strings.Split` and `strings.Join`.

Something like this for example:
```go
doc.IndentTabs()
s, err := doc.WriteToString()
prefixed := strings.Join(strings.Split(s, "\n"), "\n" + prefix)
```
