### ISSUE TITLE
Remove element, leave whitespace

### ISSUE THREAD

**Issue by danhardman** [beevik/etree#33]
In order to adhere to some stupid API, I have to provide some XML with a blank space where an element will be placed.

Is it possible to remove an element and leave its whitespace in the document? I've tried removing an element and then inserting `etree.NewElement("")` but that inserts `</>`. 

If there's a way I can do it using this library, awesome, if not I'll have to just manipulate it as a text file

**Comment by beevik** [comment]
There is not currently a way to achieve this with the etree package. It's pretty strict about the output it will generate, so it doesn't allow for extra whitespace.  Sorry.
