### ISSUE TITLE
Text filtering on leaf node

### ISSUE THREAD

**Issue by danielgblanco** [beevik/etree#35]
Given an XML like
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<library>
  <!-- Great book. -->
  <book id="b0836217462" available="true">
    <isbn>0836217462</isbn>
    <title lang="en">Being a Dog Is a Full-Time Job</title>
    <quote>I'd dog paddle the deepest ocean.</quote>
    <author id="CMS">
      <name>Charles M Schulz</name>
      <born>1922-11-26</born>
      <dead>2000-02-12</dead>
    </author>
    <character id="PP">
      <name>Peppermint Patty</name>
      <born>1966-08-22</born>
      <qualification>bold, brash and tomboyish</qualification>
    </character>
    <character id="Snoopy">
      <name>Snoopy</name>
      <born>1950-10-04</born>
      <qualification>extroverted</qualification>
      <qualification>beagle</qualification>
    </character>
  </book>
</library>
```

A query like `library/book/character[qualification='beagle']/qualification` would return all `qualification` elements of `character` for every character with a `qualification='beagle'`. It'd be good to allow `text()` XPath queries so that a query like  `library/book/character/qualification[text()='beagle']` only returns the nodes of type `qualification` which text is `beagle`.

**Comment by beevik** [comment]
Good idea. I'll add this to my TODO list.

**Comment by beevik** [comment]
ok this has been added in https://github.com/beevik/etree/commit/b7a0efda23007009c6aadd3b024b61c9aa0c5ffb

**Comment by danielgblanco** [comment]
Nice! :+1:  thanks
