### ISSUE TITLE
Extracting elements with text

### ISSUE THREAD

**Issue by npiganeau** [beevik/etree#39]
Hi, 

I have a need to retrieve all text tokens of an element and its descendant, i.e. a path looking something like `//something/text()`. 

Since `Element.FindElementsPath()` and friends returns an `Element` and not a `Token`, it would alternatively be fine if I get a list of elements with non nil text.

I'm ready to make a PR to add this functionality, but I would like to know before how you would see it.
- Should we add a new function to `Element` to retrieve Tokens from a path or should we stick to the existing functions `Element.FindElementsPath()` ?
- If we keep existing functions, should we keep the `//something/text()` syntax or a different one (since we are actually retrieving the parent of the text nodes) ? In this case, what would it be ?

Thanks

**Comment by beevik** [comment]
Does your pull request deal with all the issues you raised?

I'd prefer to avoid a new set of functions returning tokens instead of elements.  This keeps the API simple.

I'm closing this issue, so you can respond in PR #40 .
