### ISSUE TITLE
how to get all content of an element

### ISSUE THREAD

**Issue by marcelloh** [beevik/etree#41]
Is something like this possible:
```
for _, e := range doc.FindElements("./bookstore/book[1]/*") {
    fmt.Printf("%s: %s\n", e.Tag, e.Content())
}
```
Which would show the content of the given search
```
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <p:price>30.00</p:price>
```
When I do e.Text() I only get the text value, but I need it all.

**Comment by beevik** [comment]
The API is designed to access only a single XML element at a time, so you can't get all child elements as text using a single API call.

One thing you might be able to do is create a new `Document`, `Copy` the element you're interested in, and `AddElement` the copied element to the new document, then call `WriteToString` on the new document.

**Comment by marcelloh** [comment]
For people in need a a solution:

```
	tempHtml := ""
	docLoc := etree.NewDocument()
	if err := docLoc.ReadFromString(memHtml); err != nil {
		panic(err)
	}

	docCopy := etree.NewDocument()
	// repeat for every element found
	for _, t := range docLoc.FindElements(findElement) {
		newElm := t.Copy()
		docCopy.SetRoot(newElm)
		docText, _ := docCopy.WriteToString()
		tempHtml += docText
	}
```
In tempHtml is all I needed :-)
