### ISSUE TITLE
Consider returning an Error in SelectElement if the element was not found

### ISSUE THREAD

**Issue by h4xr** [beevik/etree#45]
Currently, SelectElement doesn't return anything indicating an error while trying to select an element in the XML string.
Trying to do further operations on the returned node causes the program to Panic with SEGFAULT.

For example:
Consider the following XML:
data := "<capabilities>
   <host>
      <topology cores="2" threads="2">
          <feature>vmx</feature>
      <topology>
    </host>
</capabilities>"

Now, if try to run the following code:
xmlDoc := etree.NewDocument()
	XMLReadError := xmlDoc.ReadFromString(capabilitiesXML)
	if XMLReadError != nil {
		log.Printf("Unable to read the Capabilities XML: %s", XMLReadError)
		return
	}
root := xmlDoc.SelectElement("host")
cpu := root.SelectElement("cpu")

The above code causes the program to panic with a SEGFAULT

Returning an error if the concerned element is not found seems to be a better approach to avoid these kinds of issues or this behavior can be documented that a nil is returned in case the element is not found and hence this needs to be checked.

**Comment by beevik** [comment]
It's not really documented properly, but SelectElement returns nil if the element isn't found.  Can you write your code to compare `root` to `nil` instead of comparing `err` to `nil`?

I'm reluctant to change the API now, because that would be a breaking change.

**Comment by beevik** [comment]
I updated the documentation to better indicate that `SelectElement` returns nil when the element isn't found.
