### ISSUE TITLE
Walking mechanism

### ISSUE THREAD

**Issue by SebScoFr** [beevik/etree#47]
As I understand, **ReadFromFile** stores the entire file's content in memory before we can do whatever we have to do with the nodes.
This is not ideal when dealing with very large files.

Is there currently a way to process the nodes as we _walk_ through the file, therefore avoiding the need to store it all in memory at once? Hope that makes sense

**Comment by beevik** [comment]
The `etree` package is not suited for large XML files that you don't wish to load into memory all at once.  If processing part of large XML files is your goal, your best option is probably to use go's standard XML [`Decoder`](https://golang.org/pkg/encoding/xml/#Decoder).

**Comment by SebScoFr** [comment]
Thanks, just needed a confirmation of that. 👍I'll build my own parser then with the standard library.
