### ISSUE TITLE
Please skip BOM

### ISSUE THREAD

**Issue by suntong** [beevik/etree#52]
When reading from file (via `ReadFrom()` or `ReadFromFile()`), is it possible to skip the BOM 
(https://en.wikipedia.org/wiki/Byte_order_mark) char? 

Every file created by MS under Windows has that witched char, which is very hard to get rid of. 
So it'll be great that `etree` can skip them when reading from file. 

The following file will fail:

```
$ cat et_example.xml | hexdump -C
00000000  ff fe 3c 00 62 00 6f 00  6f 00 6b 00 73 00 74 00  |..<.b.o.o.k.s.t.|
00000010  6f 00 72 00 65 00 3e 00  0d 00 0a 00 20 00 3c 00  |o.r.e.>..... .<.|
...
```

with the following error

`panic: XML syntax error on line 1: invalid UTF-8`

Hmm, wait, is it because of BOM or the UTF16 encoding? 

thx

**Comment by suntong** [comment]
I tried to convert that file to ascii myself, but got into the following problem when doing `ReadFrom()`:

    xml: encoding "utf-16" declared but Decoder.CharsetReader is nil

**Comment by suntong** [comment]
Attaching the simple example.xml file for you to try it out...

[example.zip](https://github.com/beevik/etree/files/2182255/example.zip)

**Comment by suntong** [comment]
After removing the BOM char myself, when doing `ReadFrom()`, I'll get:

    XML syntax error on line 1: expected element name after <

_"MS is the source of all evil & trouble"_. Yes, I totally agree.

**Comment by suntong** [comment]
After removing the stupid first line `<?xml version="1.0" encoding="utf-16"?>`, I'm getting:

    XML syntax error on line 1: illegal character code U+0000

```
$ head -1 et_example.xml | hexdump -C
00000000  00 3c 00 54 00 72 00 61  00 63 00 65 00 44 00 61  |.<.T.r.a.c.e.D.a|
00000010  00 74 00 61 00 20 00 78  00 6d 00 6c 00 6e 00 73  |.t.a. .x.m.l.n.s|
00000020  00 3d 00 22 00 68 00 74  00 74 00 70 00 3a 00 2f  |.=.".h.t.t.p.:./|
00000030  00 2f 00 74 00 65 00 6d  00 70 00 75 00 72 00 69  |./.t.e.m.p.u.r.i|
00000040  00 2e 00 6f 00 72 00 67  00 2f 00 54 00 72 00 61  |...o.r.g./.T.r.a|
00000050  00 63 00 65 00 50 00 65  00 72 00 73 00 69 00 73  |.c.e.P.e.r.s.i.s|
00000060  00 74 00 65 00 6e 00 63  00 65 00 2e 00 78 00 73  |.t.e.n.c.e...x.s|
00000070  00 64 00 22 00 3e 00 0d  00 0a                    |.d.".>....|
0000007a
```

Attaching the witched file:
[et_example.zip](https://github.com/beevik/etree/files/2182317/et_example.zip)

**Comment by beevik** [comment]
It looks like you're trying to read a UTF16 file.  You should probably use the `unicode/utf16` library to decode it, re-encode it to UTF8 using `unicode/utf8', and then pass it to etree.

**Comment by beevik** [comment]
Closing this file since I haven't seen a response.  Please feel free to reopen if my response doesn't help you.
