### ISSUE TITLE
Problem parsing CDATA after newline

### ISSUE THREAD

**Issue by mkadin** [beevik/etree#54]
Thanks a ton for this package - super useful for my work.

I'm parsing some RSS feeds that contain HTML contained in <!CDATA[ ... ]> tags with formatted HTML for post descriptions, content, etc.  It looks like when the CDATA tag is preceded by a newline, the text can't be parsed out:

```
	workingCDATAString := `
	<rss>
		<channel>
			<item>
		   		<summary><![CDATA[Sup]]></summary>
			</item>
		</channel>
	</rss>
	`

	doc := etree.NewDocument()
	doc.ReadFromString(workingCDATAString)
	spew.Dump(doc.FindElement("rss").FindElement("channel").FindElement("item").FindElement("summary").Text())
	// Output: (string) (len=3) "Sup"

	brokenCDATAString := `
	<rss>
		<channel>
			<item>
		   		<summary>
			 		<![CDATA[Sup]]>
				</summary>
			</item>
		</channel>
	</rss>
	`
	doc = etree.NewDocument()
	doc.ReadFromString(brokenCDATAString)
	spew.Dump(doc.FindElement("rss").FindElement("channel").FindElement("item").FindElement("summary").Text())
	// Output: (string) (len=7) "\n\t\t\t \t\t"
```

I'm not familiar with XML parsing enough to say that this isn't the intended behavior, but I would expect these two code blocks to output the same thing ("Sup").  Any ideas?

**Comment by mkadin** [comment]
Might be more than newlines, for now, I'm stripping out any whitespace before CDATA with string processing up front before passing it to etree, but would prefer a cleaner solution!  Happy to try and put together a pull request if you can help me figure out what's happening.

**Comment by beevik** [comment]
Actually I'm pretty sure this is expected behavior with XML parsing.  Anything between <tag> and </tag> is considered to be part of the tag element's text.  So the text (including the white space) surrounding your CDATA is also part of the <summary> element's text.

**Comment by mkadin** [comment]
But the content within the cdata is missing altogether when there is whitespace. That's expected?

**Comment by mkadin** [comment]
Python for instance, includes the extra tabs and spaces, but at least include the CDATA content:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> data = """<rss>
...             <channel>
...                     <item>
...                             <summary>
...                                     <![CDATA[Sup]]>
...                             </summary>
...                     </item>
...             </channel>
...     </rss>"""
>>> data
'<rss>\n\t\t<channel>\n\t\t\t<item>\n\t\t   \t\t<summary>\n\t\t\t \t\t<![CDATA[Sup]]>\n\t\t\t\t</summary>\n\t\t\t</item>\n\t\t</channel>\n\t</rss>'
>>> import xml.etree.ElementTree as ET
>>> root = ET.fromstring(data)
>>> root.find("channel").find("item").find("summary").text
'\n\t\t\t \t\tSup\n\t\t\t\t'
```

**Comment by beevik** [comment]
The CDATA should not be missing, so that would be a bug.  I'll try to take a look at this soon.

**Comment by beevik** [comment]
>Maybe should loop over all of Child and concatenate the results?

Yes, you're right. It should concatenate all consecutive CharData fields.  I'll work on a fix for this.

Thanks for checking it out.

**Comment by beevik** [comment]
This is fixed.  Thanks for the bug report, and sorry it took so long to get to it.

**Comment by mkadin** [comment]
Cool, confirmed this worked!  Ended up causing a bunch of test failures, but for the right reason!

Thanks for your help.
