### ISSUE TITLE
Text escaping not correct

### ISSUE THREAD

**Issue by crazytyper** [beevik/etree#55]
The valid character range for XML is specified as:

```
Char := #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
```

When producing XML using `WriteTo` a set of `strings.Replacer` objects in [etree.go](https://github.com/beevik/etree/blob/9750b0e2ad288eec0bc888d39b890f47849bf883/etree.go#L818) are used to escape strings.

However, these replacers fail to replace some characters that are not valid in XML (e.g. `0xB` vertical tab).

This leads to invalid XML being produced.

The go standard package `xml` replaces invalid characters with `\uFFFD` (unicode replacement character) which appears to be common practice across other XML libraries.

I propose using [`xml.EscapeText`](https://golang.org/src/encoding/xml/xml.go?s=44221:44265#L1881)  instead of the current approach based on `strings.NewReplacer(...)`.

**Comment by beevik** [comment]
This should be fixed in https://github.com/beevik/etree/commit/69ce3ef503e09b17661f017543c63d9fafc505d1

Thanks for the report!
