### ISSUE TITLE
RemoveChild() Example 

### ISSUE THREAD

**Issue by suntong** [beevik/etree#69]
Hi @beevik, 

Can you give an example using `RemoveChild()` please? 

Also, I searched those `_test` files, and seems that there is no test coverage for `RemoveChild()` either. 

thx

**Comment by suntong** [comment]
Has the `RemoveChild()` API been changed? 
Was it working with `Token` before, in V1.0.1? 
I vaguely remember it dealt with `Element` before.

**Comment by suntong** [comment]
```
	for _, e := range doc.FindElements("//MyTag") {
		doc.RemoveChild(e)
	}

	doc.WriteTo(os.Stdout)
```

What's wrong with above? 
`//MyTag` can surely be found in `doc`, but why my doc output is the same as original?

**Comment by beevik** [comment]
The problem is that the `<year>` element is not a direct child of the document.  The `RemoveChild` method only operates on direct children of an element.  To do this properly, you'd need to remove it from its parent `<book>` element.  

Good point about the missing unit tests for RemoveChild.  I will add that to my TODO list.

**Comment by hasufell** [comment]
I still see no `RemoveChild()` example in the docs. And I'm also struggling with it.

**Comment by suntong** [comment]
> I still see no `RemoveChild()` example in the docs. And I'm also struggling with it.

Yes, a `RemoveChild()` example in the docs would be better, but I'm no longer able to reopen this any more as it's not closed by me.

**Comment by beevik** [comment]
After reading this, I came to the conclusion that the existing element removal API is too difficult to use. So I added a new way to remove elements (or any token, for that matter) from the document. Simply call `Remove()` on it.

For example, given an element pointer `*e`, you can now call `e.Remove()`. It returns true if the removal was successful. (The only way it would return false is if the element had no parent element.

This also works for other token types (`Comment`, `CharData`, etc.)

Change added [here](https://github.com/beevik/etree/commit/c9eec495e5b2384759f7d59f4f5d04c866733210).
