### ISSUE TITLE
Don't deprecate InsertChild() please

### ISSUE THREAD

**Issue by suntong** [beevik/etree#70]
> Deprecated: InsertChild is deprecated. Use InsertChildAt instead.

Please don't deprecate `InsertChild()` because `InsertChildAt` won't work for my case --

The xml file that I'm working on has a rigid format of where things are:

```xml
<A attr=... >
  <B attr=... />
  <C attr=... />
  <D attr=... />
</A>
```

`B` comes before `C` which comes before `D`. I know the order doesn't matter to xml, but I'm tracking the file with version control so, I'd prefer as little change as possible. 

Whether I do `doc.InsertChildAt(0, c)` or  `doc.InsertChildAt(1, c)`, `C` will always be inserted before `B`; whereas I need it after `B` but before `D` (after I've remove `C` beforehand). 

Was I using `InsertChildAt` incorrectly, or  `InsertChild()` is just not replaceable for my case? Thx.

**Comment by suntong** [comment]
OK, i'll try again...

**Comment by suntong** [comment]
Emm... I don't know why but I can't get either works now. 

Please check out https://play.golang.org/p/EKwcUc2n3Ws
which is having signal SIGSEGV: segmentation violation error, 

while https://play.golang.org/p/S5msRioHP94
it runs but `C` is not inserted below `B`.
I tried to change `"./A"` to `"B"` on line 21,
but the result look the same as before. 

Would you show me how to insert `C` below `B` please for both cases? 
THX!

**Comment by beevik** [comment]
You had a bug.  Here is the corrected version:

https://play.golang.org/p/Z2gS6gkH2ge

**Comment by suntong** [comment]
Thanks. 

> Whether I do `doc.InsertChildAt(0, c)` or  `doc.InsertChildAt(1, c)`, `C` will always be inserted before `B`; 

The first index starts at `1`, not `0`. Thus to insert at second place, use index `2`.
