### ISSUE TITLE
Attribute namespaces broken.

### ISSUE THREAD

**Issue by thomas001** [beevik/etree#79]
In etree `Attr.NamespaceURI`, always returns the containing element's namespace. This is wrong for two reasons:

### Unprefixed attributes

Unprefixed attributes get no namespace assigned. This is different from elements. See [XML Names 6.2](https://www.w3.org/TR/xml-names/#defaulting): 

>   The namespace name for an unprefixed attribute name always has no value.

### Prefixed attributes

For prefixed attributes, the prefix should be resolved into an URI. 

### Example

Using a shortend etree test case:
```xml
<root xmlns="http://root.example.com" 
      xmlns:attrib="http://attrib.example.com" 
      a="foo" 
      attrib:b="bar" />
```

Let's use `xmlstarlet`, which is just a neat libxml2 CLI frontend.

```shell
$ xmlstarlet sel -N root=http://root.example.com -N attrib=http://attrib.example.com -N notattrib=http://attrib.example.com \
  -t -m '/root:root' \
  -o '@a[namespace-uri()=""]: ' -v '@a[namespace-uri()=""]' -nl \
  -o '@root:a[namespace-uri()="http://root.example.com"]:' -v '@root:a[namespace-uri()="http://root.example.com"]' -nl \
  -o '@b[namespace-uri()=""]:' -v '@b[namespace-uri()=""]' -nl \
  -o '@root:b[namespace-uri()="http://root.example.com"]:' -v '@root:b[namespace-uri()="http://root.example.com"]' -nl \
  -o '@attrib:b[namespace-uri()="http://attrib.example.com"]: ' -v '@attrib:b[namespace-uri()="http://attrib.example.com"]' -nl \
  -o '@notattrib:b[namespace-uri()="http://attrib.example.com"]: ' -v '@notattrib:b[namespace-uri()="http://attrib.example.com"]' -nl \
  test.xml
```

Which produces the following output:

```
@a[namespace-uri()=""]: foo
@root:a[namespace-uri()="http://root.example.com"]:
@b[namespace-uri()=""]:
@root:b[namespace-uri()="http://root.example.com"]:
@attrib:b[namespace-uri()="http://attrib.example.com"]: bar
@notattrib:b[namespace-uri()="http://attrib.example.com"]: bar
```

Note that without the test for `namespace-uri()` all of the result except the last one would be correct in etree, since etree does not resolve prefixes for attribute and element selection (a different bug).

EDIT: messed up shell quoting.

**Comment by beevik** [comment]
Thanks for the bug report. I'll take a look at this.

**Comment by beevik** [comment]
Fix committed. Thanks for the bug report.
