### ISSUE TITLE
SelectElements doesn't handle namespace properly

### ISSUE THREAD

**Issue by emersion** [beevik/etree#83]
Given this document:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<D:propfind xmlns:D="DAV:">
  <D:prop xmlns:R="http://ns.example.com/boxschema/">
    <R:bigbox/>
    <R:author/>
    <R:DingALing/>
    <R:Random/>
  <D:prop>
</D:propfind>
```

* `doc.Root().SelectElements("DAV:prop")` returns zero element
* `doc.Root().SelectElements("D:prop")` returns one element

However the `D` prefix is arbitrary, it could be set to any token really (e.g. `xmlns:myawesomeprefix="DAV:"`). `SelectElements` shouldn't care about it, it should resolve the prefix depending on `xmlns` attributes.

https://play.golang.org/p/I8XUmLjY9pX

**Comment by beevik** [comment]
I believe this is the same issue as https://github.com/beevik/etree/issues/81.  Please reopen if you disagree.
