### ISSUE TITLE
Need help with the license

### ISSUE THREAD

**Issue by pvillads** [beevik/etree#84]
Hi,

I like the way that this works on go, since I have used the same approach in python. However, I am not sure what the requirements are using your library. You are not using a standard license, but one that bears your name. Is there any reason why you did not use the MIT license, or any other permissive license? What do I need to do on a github site that consumes your code?

**Comment by Ferada** [comment]
It's the standard [2-clause / Simplified BSD License](https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)). It's what it says in the text of it?

**Comment by pvillads** [comment]
Ferada,

Thank you for answering. I find no mention in the license file of it being the 2-clause / Simplified BSD license, and I did not recognize it as such. 

The text has the preamble:
Copyright 2015-2019 Brett Vickers. All rights reserved.

before the text. It was not obvious that it is the license you mention. I thought it was a random license created by the Brett Vickers.

I am happy with this permissive license.

Thanks again.
