### ISSUE TITLE
When does ReadFromString return error?

### ISSUE THREAD

**Issue by konaraya** [beevik/etree#87]
When using ReadFromString on improper XML, no error is returned. Is this expected? 
Sample code:
```
improperXML := "<support>SOS"
doc := etree.NewDocument()
err := doc.ReadFromString(improperXML)
```
err in the above case is nil. Is this expected? encoding/xml 's Unmarshall returns an error for the same string:
```
XML syntax error on line 1: unexpected EOF
```
[etree play link](https://play.golang.org/p/BR1aLsJ7f1u)
[encoding/xml play link](https://play.golang.org/p/b4IOMxb7qCL)

**Comment by beevik** [comment]
This is a bug.  Working on a fix.

**Comment by beevik** [comment]
Ok I've checked in a fix for this bug. Thanks for the bug report.
