### ISSUE TITLE
DeepEquals

### ISSUE THREAD

**Issue by adolsalamanca** [beevik/etree#90]
Hello,

In our team, we have started using this module to work with our XML files.

As part of our development process, we have performed a lot of tests using etree, and we end up with a function to perform DeepEquals between elements. 

Would you be open to include it as part of this module?
In our case, is an anonymous function, but it could be a method of Element type also.

Thanks,
Regards.

Adolfo

**Comment by beevik** [comment]
Can you explain a little bit more about how you view this working?

1. Does it care about the order of element attributes?
2. Does it care about white-space between elements?

I can imagine a `Compare` method on `Element` that accepts various parameters configuring the way the comparison behaves.

**Comment by adolsalamanca** [comment]
Hi Brett,

First of all, thanks for the fast response.
As of now, it performs a recursive comparison between all the nodes and its attributes, till it reaches a node with no childs
Once this is confirmed, then it compares the childs of every node ensuring that all have the same attributes.

About your questions : 
- Currently it does not take in account the order of the attributes, it just check if the attributes in the first element xpath are present in the equivalent xpath of the second one.
- Regarding the white-spaces between elements I'm not pretty sure, you mean the inside text of an element? If this was the case I think that would make the current IsDeepEquals func return false, but if you mean spaces between nodes I'm not pretty about that.

Your idea sounds great, it could be an Element method that receives the element to be compared with and also a few configuration params. 

Would you like to see the first draft as a PR or how would like to proceed with this?
Thanks again,
Regards.

**Comment by adolsalamanca** [comment]
Update, I have checked both the comment and the current function and as of now, it is ignoring the whitespaces between elements, but we could change this behavior if needed.
Thanks,

Adolfo

**Comment by beevik** [comment]
If you already have a change you'd like me to look at, then please submit the pull request.  It will be easier to suggest changes that way.

Thanks!
