### ISSUE TITLE
when write to file the cdata tag were removed 

### ISSUE THREAD

**Issue by yudar1024** [beevik/etree#92]
```go
	log.Print("this is a log")
	doc := etree.NewDocument()
	if err := doc.ReadFromFile("D:\\Program\\FineReport_10.0\\webapps\\webroot\\WEB-INF\\reportlets\\books\\stock_detail_daily.cptx"); err != nil {
		panic(err)
	}
	databaseName := doc.FindElements("./WorkBook/TableDataMap/TableData/Connection/DatabaseName")
	for _, element := range databaseName {
		log.Print(element.Text())
		content := strings.Split(element.Text(), ".")
		log.Println(content)
		element.SetText(content[0])
	}
	doc.WriteToFile("D:\\Program\\FineReport_10.0\\webapps\\webroot\\WEB-INF\\reportlets\\books\\stock_detail_daily.cptx")
```
xml content origin
```xml
<Border>
<Top style="1" color="-4144960"/>
<Bottom style="1" color="-4144960"/>
<Left style="1" color="-4144960"/>
<Right style="1" color="-4144960"/>
</Border>
</Style>
<Style horizontal_alignment="0" imageLayout="1">
<Format class="com.fr.base.CoreDecimalFormat" roundingMode="6">
<![CDATA[#0.00]]></Format>
<FRFont name="SimSun" style="0" size="72"/>
```
xml content after run program
```xml
<Background name="NullBackground"/>
<Border>
<Top style="1" color="-4144960"/>
<Bottom style="1" color="-4144960"/>
<Left style="1" color="-4144960"/>
<Right style="1" color="-4144960"/>
</Border>
</Style>
<Style horizontal_alignment="0" imageLayout="1">
<Format class="com.fr.base.CoreDecimalFormat" roundingMode="6">
#0.00</Format>
```

**Comment by beevik** [comment]
Your call to `SetText()` is causing the `CDATA` token to be stripped.  Try using `SetCData()` instead.

**Comment by yudar1024** [comment]
> Your call to `SetText()` is causing the `CDATA` token to be stripped. Try using `SetCData()` instead.

I mean the original xml file already has many CDATA tag, after I load them in etree and write to another new file with out any modification, the CDATA tags were removed. how can I keep the original CDATA when I write to a new file

**Comment by skyy-x** [comment]
Because etree is using xml decoder, the decoder gets element content of `CDATA` only.
see [https://github.com/golang/go/blob/master/src/encoding/xml/xml.go#L704](url)
`text(-1, true)` will strip `CDATA` token

**Comment by james-lawrence** [comment]
@beevik this is a problem and not handling cdata properly breaks many xml documents.

@skyy-x if you look like 2 lines below you'll see the node type returned is CDATA. fixing this should be as easy as checking for xml.CData type and then emitting the prefix + suffix.

**Comment by skyy-x** [comment]
> @beevik this is a problem and not handling cdata properly breaks many xml documents.
> 
> @skyy-x if you look like 2 lines below you'll see the node type returned is CDATA. fixing this should be as easy as checking for xml.CData type and then emitting the prefix + suffix.

https://github.com/golang/go/blob/master/src/encoding/xml/xml.go#L572

**Comment by james-lawrence** [comment]
ah my apologies. you can look here https://github.com/antchfx/xmlquery/blob/master/parse.go#L195 for an implementation around CharData for detecting cdata elements.

**Comment by mmandolesi-g** [comment]
I am having the same issue where the CDATA tags are being stripped from the whole XML document. Is there any workaround or fix?

**Comment by abiramisinnarajan** [comment]
I am also having similar issue where the CDATA tags are being stripped from the whole XML document. Is there any workaround or fix?

**Comment by beevik** [comment]
Unfortunately, the XML decoder this package is built on (`encoding/xml`) produces tokens that strip out the distinction between character data and CDATA elements.  See https://pkg.go.dev/encoding/xml#Token.  I am not aware of any way to obtain this information while decoding using the go XML decoder.
