### ISSUE TITLE
Getting the following-sibling

### ISSUE THREAD

**Issue by suntong** [beevik/etree#99]
Xpath [supports `following-sibling`](https://stackoverflow.com/a/47628382/2125837). How can I do that with etree?

In [a typical jmx file](https://github.com/LusithaP/test/blob/3cf8eaec5a78fd27431ac8432a2f8ab2a2080949/WillAll/apache-jmeter-3.3/bin/Sample.jmx), 
`<hashTree>` can exist any where. I want to locate the `<hashTree>`  that following a certain `<TransactionController>`, 
say [`testname="T01_LandingPage"`](https://github.com/LusithaP/test/blob/3cf8eaec5a78fd27431ac8432a2f8ab2a2080949/WillAll/apache-jmeter-3.3/bin/Sample.jmx)

Is it possible? Thx

**Comment by beevik** [comment]
Not currently possible, sorry.
